### ISSUE TITLE
Building fails von MacOS BigSur

### ISSUE THREAD

**Issue by omichels** [lucasepe/draft#9]
`go generate ../...
/usr/local/Cellar/statik/0.23.0_3/libexec/lib/python3.9/site-packages/sqlalchemy/orm/query.py:196: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if entities is not ():
usage: statik [-h] [-p PROJECT] [--quickstart] [--autogen] [-o OUTPUT] [--clear-output] [-s] [-w] [--host HOST] [--port PORT] [--no-browser]
              [--deploy {sftp,netlify}] [-v] [--quiet] [--fail-silently] [--no-colorlog] [--version]
statik: error: argument -s/--safe-mode: ignored explicit argument 'rc=./assets'
../icon.go:3: running "statik": exit status 2
> which statik
/usr/local/bin/statik
`

**Comment by lucasepe** [comment]
I don't have a macOS, I'm a linux (Debian) user, but (this is an hypothesis) from what you have reported it seems that on your laptop you have installed a "pythonic" tool called (since the Universe is a jester :-) ...) 'statik'.
Maybe this? (https://pypi.org/project/statik/) while the go tool is this https://github.com/rakyll/statik...

**Comment by lucasepe** [comment]
I'm closing this since no more feedbacks, eventually we will repoen it. Thanks!
